### ISSUE TITLE
please check my pull request

### ISSUE THREAD

**Issue by neilkerman** [samanshk/calculator_app_flutter#6]
Hello there,
I have updated your readme. I worked hard for it, please consider my pull request.
Thanks.

**Comment by neilkerman** [comment]
Hello,
My PR now has a conflict, please resolve the conflict and merge the request.
Thanks!

**Comment by samanshk** [comment]
I tried resolving the conflict but it is not working out. I think you should fork this repository, create a new branch, make changes to that branch and make new PR.

**Comment by neilkerman** [comment]
> I tried resolving the conflict but it is not working out. I think you should fork this repository, create a new branch, make changes to that branch and make new PR.

Alright, can you give me write access to this repository? I can try to merge the conflicts. Just invite me as a collaborator, that would do probably
